Feat/cf 522 eslint design i18n
360medics/inapp-cli pull request #16
Opened 2022-11-15 15:22 UTC by theorosset

2022-11-16 09:00 UTC, charlesgourdin commented on cli/boilerplate/stacks/client/src/App.vue
> +    }
Profite que l'on fasse du SCSS pour bien nester tes classes. Tu peux en profiter pour faire du BEM!
loader-content__spinner par exemple

2022-11-16 09:02 UTC, charlesgourdin commented on cli/boilerplate/stacks/client/src/components/HeaderComponent.vue
> +            return route.path !== '/'
@marc360medics c'est pas le soucis que tu as rencontré avec l'API key?

2022-11-16 09:03 UTC, charlesgourdin commented on cli/boilerplate/stacks/client/src/components/HeaderComponent.vue
> +.header-bg {
Même remarque pour le style, à toi de voir si tu peux cleaner un peu (si compatible avec ton linter obviously)

2022-11-16 09:04 UTC, charlesgourdin commented on cli/boilerplate/stacks/client/src/i18n/index.ts
> +const getNavigatorLanguage = () => {
Quand tu peux, pense à typer tes sorties de méthode

2022-11-16 09:05 UTC, charlesgourdin commented on cli/boilerplate/stacks/client/src/main.ts
> +createApp(App).use(store).use(router).use(i18n).mount('#app')
On peut indenter ici avec des retours à la ligne

2022-11-17 07:56 UTC, theorosset commented on cli/boilerplate/stacks/client/src/components/HeaderComponent.vue
> +            return route.path !== '/'
vue avec @marc360medics il dit que non

2022-12-07 14:28 UTC, charlesgourdin approved these changes

2022-12-07 14:28 UTC, charlesgourdin commented on cli/boilerplate/stacks/client/src/App.vue
> +            <div class="loader-content page-content" v-else>
C'est bien de mettre les directives en premier pour faciliter la lecture. 
Là par exemple, je cherchais le v-else...

2022-12-07 14:28 UTC, charlesgourdin commented on cli/boilerplate/stacks/client/src/i18n/index.ts
> +}
On peut pas retourner en si jamais on ne trouve rien plutôt que undefined?

2022-12-07 16:13 UTC, Pascal-Legroux requested changes
il semble que le eslint ne soit pas configuré correctement
pb de saut de ligne à la fin des fichiers non signalé ?
code en commentaire inutile
voir le fallback sur "en" en cas d'absence de lang

2022-12-07 16:13 UTC, Pascal-Legroux commented on cli/boilerplate/stacks/client/src/components/ScoreList.vue
> +    //box-shadow: $submenu_item_shadow;
supprimer l'élément en commentaire

2022-12-07 16:13 UTC, Pascal-Legroux commented on cli/boilerplate/stacks/client/src/i18n/index.ts
> +}
+1

2022-12-07 16:13 UTC, Pascal-Legroux commented on cli/boilerplate/stacks/client/src/sass/helpers/_variables.scss
>  $button_corner: 8px;
il manque un ligne à la fin du fichier
pb eslint

2022-12-07 16:13 UTC, Pascal-Legroux commented on stacks/client/src/assets/locales/fr.json
> +}
il manque un ligne à la fin du fichier
pb eslint

2022-12-07 16:13 UTC, Pascal-Legroux commented on stacks/client/src/components/ScoreList.vue
> +    //box-shadow: $submenu_item_shadow;
même remarque que précédemment
supprimer cet élément en commentaire

2022-12-12 16:05 UTC, theorosset commented on stacks/client/src/assets/locales/fr.json
> +}
il manque un e a 'une ligne'  😂

2022-12-12 16:08 UTC, theorosset commented on cli/boilerplate/stacks/client/src/sass/helpers/_variables.scss
>  $button_corner: 8px;
il manque un 'e' a 'une ligne' 😂

2022-12-12 16:19 UTC, CyprienFloquet commented on cli/boilerplate/stacks/client/src/sass/helpers/_variables.scss
>  $button_corner: 8px;
@theorosset  tu joues avec le feu là

2022-12-12 16:19 UTC, CyprienFloquet commented on cli/boilerplate/stacks/client/src/sass/helpers/_variables.scss
>  $button_corner: 8px;
Autement ce serait bien d'avoir la même convention de nommage pour les variables

2022-12-13 10:14 UTC, Pascal-Legroux commented on cli/boilerplate/stacks/client/src/sass/helpers/_variables.scss
>  $button_corner: 8px;
> @theorosset tu joues avec le feu là

laisse le petit s'amuser :)

2023-01-11 14:56 UTC, marc360medics approved these changes

2023-01-12 09:57 UTC, merged